/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package dnsway-pc/internal/android */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 5 "bridge.go"

#include <jni.h>
#include <stdlib.h>
#include <string.h>

// JNI wrapper helpers (JNI functions must be called through the env function table)
static const char* jni_get_string_utf_chars(JNIEnv* env, jstring js, jboolean* isCopy) {
    return (*env)->GetStringUTFChars(env, js, isCopy);
}

static void jni_release_string_utf_chars(JNIEnv* env, jstring js, const char* chars) {
    (*env)->ReleaseStringUTFChars(env, js, chars);
}

static jstring jni_new_string_utf(JNIEnv* env, const char* chars) {
    return (*env)->NewStringUTF(env, chars);
}

static jboolean jni_get_boolean_field(JNIEnv* env, jobject obj, jfieldID field) {
    return (*env)->GetBooleanField(env, obj, field);
}

static jfieldID jni_get_field_id(JNIEnv* env, jclass clazz, const char* name, const char* sig) {
    return (*env)->GetFieldID(env, clazz, name, sig);
}

static jclass jni_find_class(JNIEnv* env, const char* name) {
    return (*env)->FindClass(env, name);
}

static void jni_call_void_method(JNIEnv* env, jobject obj, jmethodID method, ...) {
    va_list args;
    va_start(args, method);
    (*env)->CallVoidMethodV(env, obj, method, args);
    va_end(args);
}

static jmethodID jni_get_method_id(JNIEnv* env, jclass clazz, const char* name, const char* sig) {
    return (*env)->GetMethodID(env, clazz, name, sig);
}

static jobject jni_get_object_field(JNIEnv* env, jobject obj, jfieldID field) {
    return (*env)->GetObjectField(env, obj, field);
}

// Direct JNI call wrappers for the functions used by the Go code
static const char* call_GetStringUTFChars(JNIEnv* env, jstring js) {
    return (*env)->GetStringUTFChars(env, js, NULL);
}

static void call_ReleaseStringUTFChars(JNIEnv* env, jstring js, const char* s) {
    (*env)->ReleaseStringUTFChars(env, js, s);
}

static jstring call_NewStringUTF(JNIEnv* env, const char* s) {
    return (*env)->NewStringUTF(env, s);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern jboolean Java_com_dnsway_app_engine_DnsEngine_nativeInit(JNIEnv* env, jclass cls, jstring dataDir);
extern jint Java_com_dnsway_app_engine_DnsEngine_nativeLoadCategories(JNIEnv* env, jclass cls, jstring path);
extern jstring Java_com_dnsway_app_engine_DnsEngine_nativeProcessDomain(JNIEnv* env, jclass cls, jstring domain);
extern jboolean Java_com_dnsway_app_engine_DnsEngine_nativeAddAllowlist(JNIEnv* env, jclass cls, jstring domain);
extern jboolean Java_com_dnsway_app_engine_DnsEngine_nativeRemoveAllowlist(JNIEnv* env, jclass cls, jstring domain);
extern jboolean Java_com_dnsway_app_engine_DnsEngine_nativeAddDenylist(JNIEnv* env, jclass cls, jstring domain, jstring reason);
extern jboolean Java_com_dnsway_app_engine_DnsEngine_nativeRemoveDenylist(JNIEnv* env, jclass cls, jstring domain);
extern jboolean Java_com_dnsway_app_engine_DnsEngine_nativeSetCategory(JNIEnv* env, jclass cls, jstring categoryID, jboolean enabled);
extern jstring Java_com_dnsway_app_engine_DnsEngine_nativeGetStats(JNIEnv* env, jclass cls);
extern jboolean Java_com_dnsway_app_engine_DnsEngine_nativeShouldSafeSearch(JNIEnv* env, jclass cls, jstring domain);
extern void Java_com_dnsway_app_engine_DnsEngine_nativeSetSafeSearch(JNIEnv* env, jclass cls, jboolean enabled);

#ifdef __cplusplus
}
#endif
